### ISSUE TITLE
TypeError: range_1.default is not a constructor

### ISSUE THREAD

**Issue by Jedliu** [Siemienik/XToolset#220]
Hi @Siemienik , I'm trying to include this in the nx project and do the tests to add image insertion. It's using Jest for testing and there is an error
```
TypeError: range_1.default is not a constructor
```
in `xlsx-renderer/src/Scope.ts` so the tests failed. 

I tried to include the Range def in `index.d.ts` of `exceljs` package but it didn't work.

Do you have a clue how to fix this? Thank you very much!

<img width="1369" alt="图片" src="https://user-images.githubusercontent.com/771703/205317591-1240f6e0-8b24-45e8-9bc9-cc058dd8cbb9.png">

**Comment by Siemienik** [comment]
Are you able to link the repo?

**Comment by Jedliu** [comment]
Hi @Siemienik, thanks for your fast reply. I will create a repo for your reference soon.

**Comment by Jedliu** [comment]
I solved this by forking exceljs and do a patch then install from this patch. Thanks for your attention.
Here is a link to the [patch release](https://github.com/Jedliu/exceljs/releases/tag/v4.3.0-export-doc-range)

_PS: exceljs hasn't been updated for quite a long time._

**Comment by Siemienik** [comment]
@Jedliu, Thanks for info.

Recently I started to organize Merge Fest for my projects, including exceljs. The MergeFests are organized and announced on our Discord: https://discord.gg/siema . Today I will do next one at 8pm CEST. Join us if you would like. Especially if have you got some propositions which PRs are more important than rest, just send me a link on #exceljs channel.

As I can't release `exceljs`, I started to release it as `@siema-team/spreadsheets`, GH: https://github.com/SiemaTeam/spreadsheets

Would you mind send me a link to PR with your fixation? or open new PR if doesn't exist?

Regards

**Comment by Jedliu** [comment]
Hi, Siemienik. Thanks for getting in touch with me. I will look into this when I have spare time.
