### ISSUE TITLE
Add `Import.getFirst(cfg)` function

### ISSUE THREAD

**Issue by Siemienik** [Siemienik/XToolset#81]
# Function `getFirst`

## Current:

```ts
const author = importer.getAllItems<Person>(config.owner)[0];
```

## After:

```ts
const author = importer.getFirst<Person>(config.owner);
```

## Todo:

* Add getFirst function into `IImporter` interface (not in `IImporterLegacy`)
* Implement getFist in a `Importer` class (not in `ImporterLegacy`)
* Update sample in Readme (use getFist)
* Update/Add at least one test which check it.

_For making a reservation please open draft PR with this issue linked_

**Comment by iLorah** [comment]
Hey I'll grab this one :)

**Comment by Siemienik** [comment]
> Hey I'll grab this one :)

It' nice to read that :) Good luck,

Could I please you to create draft PR?
